import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Script from 'next/script'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Mercy_Feven Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        <Script id='chatling-config' strategy='beforeInteractive'>
          {`
    window.chtlConfig = {
      chatbotId: "5944467262"
    };
  `}
        </Script>

        {/* Chatling embed */}
        <Script
          id='chatling-script'
          src='https://chatling.ai/js/embed.js'
          strategy='afterInteractive'
        />
      </body>
    </html>
  )
}
